# Generated by Django 3.2.5 on 2021-07-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_price', models.FloatField()),
                ('product_details', models.CharField(max_length=30)),
                ('product_photo', models.ImageField(upload_to='product_image')),
            ],
        ),
    ]
